version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:3000

  redis:
    image: redis
    ports:
      - ${FORWARD_QUEUE_PORT}:6379
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--replica-read-only",
        "no"
      ]
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: on-failure
